package com.myfarm.flashsale.core.modules.payment.model;

import java.util.Date;

public class Payment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment.payment_id
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    private Object paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment.payment
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    private String payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment.payno
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    private String payno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment.create_date
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment.payment_id
     *
     * @return the value of public.payment.payment_id
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    public Object getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment.payment_id
     *
     * @param paymentId the value for public.payment.payment_id
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    public void setPaymentId(Object paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment.payment
     *
     * @return the value of public.payment.payment
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment.payment
     *
     * @param payment the value for public.payment.payment
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment.payno
     *
     * @return the value of public.payment.payno
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    public String getPayno() {
        return payno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment.payno
     *
     * @param payno the value for public.payment.payno
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    public void setPayno(String payno) {
        this.payno = payno == null ? null : payno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment.create_date
     *
     * @return the value of public.payment.create_date
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment.create_date
     *
     * @param createDate the value for public.payment.create_date
     *
     * @mbg.generated Tue Feb 02 09:55:50 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}