package com.myfarm.flashsale.core.modules.site.model;

public class Site {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.site.site_id
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    private Object siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.site.name
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.site.telphone
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.site.address
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.site.operating_status
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    private String operatingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.site.site_pic
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    private Object sitePic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.site.leader
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.site.comments
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.site.site_id
     *
     * @return the value of public.site.site_id
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public Object getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.site.site_id
     *
     * @param siteId the value for public.site.site_id
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public void setSiteId(Object siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.site.name
     *
     * @return the value of public.site.name
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.site.name
     *
     * @param name the value for public.site.name
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.site.telphone
     *
     * @return the value of public.site.telphone
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.site.telphone
     *
     * @param telphone the value for public.site.telphone
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.site.address
     *
     * @return the value of public.site.address
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.site.address
     *
     * @param address the value for public.site.address
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.site.operating_status
     *
     * @return the value of public.site.operating_status
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public String getOperatingStatus() {
        return operatingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.site.operating_status
     *
     * @param operatingStatus the value for public.site.operating_status
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public void setOperatingStatus(String operatingStatus) {
        this.operatingStatus = operatingStatus == null ? null : operatingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.site.site_pic
     *
     * @return the value of public.site.site_pic
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public Object getSitePic() {
        return sitePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.site.site_pic
     *
     * @param sitePic the value for public.site.site_pic
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public void setSitePic(Object sitePic) {
        this.sitePic = sitePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.site.leader
     *
     * @return the value of public.site.leader
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.site.leader
     *
     * @param leader the value for public.site.leader
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.site.comments
     *
     * @return the value of public.site.comments
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.site.comments
     *
     * @param comments the value for public.site.comments
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}