package com.myfarm.flashsale.core.modules.user.repository.mappers;

import com.myfarm.flashsale.core.modules.user.model.UserProfile;
import com.myfarm.flashsale.core.modules.user.model.UserProfileExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    long countByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    int deleteByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    int deleteByPrimaryKey(Object userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    int insert(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    int insertSelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    List<UserProfile> selectByExample(UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    UserProfile selectByPrimaryKey(Object userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserProfile record, @Param("example") UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    int updateByExample(@Param("record") UserProfile record, @Param("example") UserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    int updateByPrimaryKeySelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_profile
     *
     * @mbg.generated Fri Jan 22 16:13:05 CST 2021
     */
    int updateByPrimaryKey(UserProfile record);
}