package com.myfarm.flashsale.core.modules.user.repository.mappers;

import com.myfarm.flashsale.core.modules.user.model.UserRole;
import com.myfarm.flashsale.core.modules.user.model.UserRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    long countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    int deleteByPrimaryKey(Object roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    UserRole selectByPrimaryKey(Object roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_role
     *
     * @mbg.generated Sat Jan 23 16:36:08 CST 2021
     */
    int updateByPrimaryKey(UserRole record);
}