package com.myfarm.flashsale.core.modules.order.repository.mappers;

import com.myfarm.flashsale.core.modules.order.model.OrderDetail;
import com.myfarm.flashsale.core.modules.order.model.OrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    long countByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    int deleteByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    int deleteByPrimaryKey(Object orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    OrderDetail selectByPrimaryKey(Object orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    int updateByExample(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Tue Feb 02 09:57:33 CST 2021
     */
    int updateByPrimaryKey(OrderDetail record);
}