package com.myfarm.flashsale.core.modules.order.repository.mappers;

import com.myfarm.flashsale.core.modules.order.model.ProdOrder;
import com.myfarm.flashsale.core.modules.order.model.ProdOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProdOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    long countByExample(ProdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    int deleteByExample(ProdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    int deleteByPrimaryKey(Object orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    int insert(ProdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    int insertSelective(ProdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    List<ProdOrder> selectByExample(ProdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    ProdOrder selectByPrimaryKey(Object orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    int updateByExampleSelective(@Param("record") ProdOrder record, @Param("example") ProdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    int updateByExample(@Param("record") ProdOrder record, @Param("example") ProdOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    int updateByPrimaryKeySelective(ProdOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prod_order
     *
     * @mbg.generated Fri Jan 22 17:49:56 CST 2021
     */
    int updateByPrimaryKey(ProdOrder record);
}