package com.myfarm.flashsale.core.modules.production.model;

public class Band {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.band.band_id
     *
     * @mbg.generated Fri Jan 29 09:21:21 CST 2021
     */
    private Object bandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.band.name
     *
     * @mbg.generated Fri Jan 29 09:21:21 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.band.band_id
     *
     * @return the value of public.band.band_id
     *
     * @mbg.generated Fri Jan 29 09:21:21 CST 2021
     */
    public Object getBandId() {
        return bandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.band.band_id
     *
     * @param bandId the value for public.band.band_id
     *
     * @mbg.generated Fri Jan 29 09:21:21 CST 2021
     */
    public void setBandId(Object bandId) {
        this.bandId = bandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.band.name
     *
     * @return the value of public.band.name
     *
     * @mbg.generated Fri Jan 29 09:21:21 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.band.name
     *
     * @param name the value for public.band.name
     *
     * @mbg.generated Fri Jan 29 09:21:21 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}