package com.myfarm.flashsale.core.modules.production.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.category.category_id
     *
     * @mbg.generated Fri Jan 29 09:22:42 CST 2021
     */
    private Object categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.category.name
     *
     * @mbg.generated Fri Jan 29 09:22:42 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.category.category_id
     *
     * @return the value of public.category.category_id
     *
     * @mbg.generated Fri Jan 29 09:22:42 CST 2021
     */
    public Object getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.category.category_id
     *
     * @param categoryId the value for public.category.category_id
     *
     * @mbg.generated Fri Jan 29 09:22:42 CST 2021
     */
    public void setCategoryId(Object categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.category.name
     *
     * @return the value of public.category.name
     *
     * @mbg.generated Fri Jan 29 09:22:42 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.category.name
     *
     * @param name the value for public.category.name
     *
     * @mbg.generated Fri Jan 29 09:22:42 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}