package com.myfarm.flashsale.core.modules.production.model;

import java.util.Date;

public class Production {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.production_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Object productionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.title
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.pic_group_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Object picGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.category_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Object categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.band_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Object bandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.place_origin
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private String placeOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.recommendation
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private String recommendation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.shelf_life
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private String shelfLife;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.date_package
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Date datePackage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.date_presell
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Date datePresell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.date_delivery
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Date dateDelivery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.price
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.original_price
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Double originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.unit
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.rank
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.stock
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.sales_volume
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Integer salesVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.status_on_shelf
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private String statusOnShelf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.provider_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Object providerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.audit_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Object auditId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.create_date
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.production.update_date
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.production_id
     *
     * @return the value of public.production.production_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Object getProductionId() {
        return productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.production_id
     *
     * @param productionId the value for public.production.production_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setProductionId(Object productionId) {
        this.productionId = productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.title
     *
     * @return the value of public.production.title
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.title
     *
     * @param title the value for public.production.title
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.pic_group_id
     *
     * @return the value of public.production.pic_group_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Object getPicGroupId() {
        return picGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.pic_group_id
     *
     * @param picGroupId the value for public.production.pic_group_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setPicGroupId(Object picGroupId) {
        this.picGroupId = picGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.category_id
     *
     * @return the value of public.production.category_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Object getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.category_id
     *
     * @param categoryId the value for public.production.category_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setCategoryId(Object categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.band_id
     *
     * @return the value of public.production.band_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Object getBandId() {
        return bandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.band_id
     *
     * @param bandId the value for public.production.band_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setBandId(Object bandId) {
        this.bandId = bandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.place_origin
     *
     * @return the value of public.production.place_origin
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public String getPlaceOrigin() {
        return placeOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.place_origin
     *
     * @param placeOrigin the value for public.production.place_origin
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setPlaceOrigin(String placeOrigin) {
        this.placeOrigin = placeOrigin == null ? null : placeOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.recommendation
     *
     * @return the value of public.production.recommendation
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public String getRecommendation() {
        return recommendation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.recommendation
     *
     * @param recommendation the value for public.production.recommendation
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setRecommendation(String recommendation) {
        this.recommendation = recommendation == null ? null : recommendation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.shelf_life
     *
     * @return the value of public.production.shelf_life
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public String getShelfLife() {
        return shelfLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.shelf_life
     *
     * @param shelfLife the value for public.production.shelf_life
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setShelfLife(String shelfLife) {
        this.shelfLife = shelfLife == null ? null : shelfLife.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.date_package
     *
     * @return the value of public.production.date_package
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Date getDatePackage() {
        return datePackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.date_package
     *
     * @param datePackage the value for public.production.date_package
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setDatePackage(Date datePackage) {
        this.datePackage = datePackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.date_presell
     *
     * @return the value of public.production.date_presell
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Date getDatePresell() {
        return datePresell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.date_presell
     *
     * @param datePresell the value for public.production.date_presell
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setDatePresell(Date datePresell) {
        this.datePresell = datePresell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.date_delivery
     *
     * @return the value of public.production.date_delivery
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Date getDateDelivery() {
        return dateDelivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.date_delivery
     *
     * @param dateDelivery the value for public.production.date_delivery
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setDateDelivery(Date dateDelivery) {
        this.dateDelivery = dateDelivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.price
     *
     * @return the value of public.production.price
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.price
     *
     * @param price the value for public.production.price
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.original_price
     *
     * @return the value of public.production.original_price
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Double getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.original_price
     *
     * @param originalPrice the value for public.production.original_price
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setOriginalPrice(Double originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.unit
     *
     * @return the value of public.production.unit
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.unit
     *
     * @param unit the value for public.production.unit
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.rank
     *
     * @return the value of public.production.rank
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.rank
     *
     * @param rank the value for public.production.rank
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.stock
     *
     * @return the value of public.production.stock
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.stock
     *
     * @param stock the value for public.production.stock
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.sales_volume
     *
     * @return the value of public.production.sales_volume
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Integer getSalesVolume() {
        return salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.sales_volume
     *
     * @param salesVolume the value for public.production.sales_volume
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setSalesVolume(Integer salesVolume) {
        this.salesVolume = salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.status_on_shelf
     *
     * @return the value of public.production.status_on_shelf
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public String getStatusOnShelf() {
        return statusOnShelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.status_on_shelf
     *
     * @param statusOnShelf the value for public.production.status_on_shelf
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setStatusOnShelf(String statusOnShelf) {
        this.statusOnShelf = statusOnShelf == null ? null : statusOnShelf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.provider_id
     *
     * @return the value of public.production.provider_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Object getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.provider_id
     *
     * @param providerId the value for public.production.provider_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setProviderId(Object providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.audit_id
     *
     * @return the value of public.production.audit_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Object getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.audit_id
     *
     * @param auditId the value for public.production.audit_id
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setAuditId(Object auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.create_date
     *
     * @return the value of public.production.create_date
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.create_date
     *
     * @param createDate the value for public.production.create_date
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.production.update_date
     *
     * @return the value of public.production.update_date
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.production.update_date
     *
     * @param updateDate the value for public.production.update_date
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}