package com.myfarm.flashsale.core.modules.production.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProductionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public ProductionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andProductionIdIsNull() {
            addCriterion("production_id is null");
            return (Criteria) this;
        }

        public Criteria andProductionIdIsNotNull() {
            addCriterion("production_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductionIdEqualTo(Object value) {
            addCriterion("production_id =", value, "productionId");
            return (Criteria) this;
        }

        public Criteria andProductionIdNotEqualTo(Object value) {
            addCriterion("production_id <>", value, "productionId");
            return (Criteria) this;
        }

        public Criteria andProductionIdGreaterThan(Object value) {
            addCriterion("production_id >", value, "productionId");
            return (Criteria) this;
        }

        public Criteria andProductionIdGreaterThanOrEqualTo(Object value) {
            addCriterion("production_id >=", value, "productionId");
            return (Criteria) this;
        }

        public Criteria andProductionIdLessThan(Object value) {
            addCriterion("production_id <", value, "productionId");
            return (Criteria) this;
        }

        public Criteria andProductionIdLessThanOrEqualTo(Object value) {
            addCriterion("production_id <=", value, "productionId");
            return (Criteria) this;
        }

        public Criteria andProductionIdIn(List<Object> values) {
            addCriterion("production_id in", values, "productionId");
            return (Criteria) this;
        }

        public Criteria andProductionIdNotIn(List<Object> values) {
            addCriterion("production_id not in", values, "productionId");
            return (Criteria) this;
        }

        public Criteria andProductionIdBetween(Object value1, Object value2) {
            addCriterion("production_id between", value1, value2, "productionId");
            return (Criteria) this;
        }

        public Criteria andProductionIdNotBetween(Object value1, Object value2) {
            addCriterion("production_id not between", value1, value2, "productionId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdIsNull() {
            addCriterion("pic_group_id is null");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdIsNotNull() {
            addCriterion("pic_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdEqualTo(Object value) {
            addCriterion("pic_group_id =", value, "picGroupId");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdNotEqualTo(Object value) {
            addCriterion("pic_group_id <>", value, "picGroupId");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdGreaterThan(Object value) {
            addCriterion("pic_group_id >", value, "picGroupId");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdGreaterThanOrEqualTo(Object value) {
            addCriterion("pic_group_id >=", value, "picGroupId");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdLessThan(Object value) {
            addCriterion("pic_group_id <", value, "picGroupId");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdLessThanOrEqualTo(Object value) {
            addCriterion("pic_group_id <=", value, "picGroupId");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdIn(List<Object> values) {
            addCriterion("pic_group_id in", values, "picGroupId");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdNotIn(List<Object> values) {
            addCriterion("pic_group_id not in", values, "picGroupId");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdBetween(Object value1, Object value2) {
            addCriterion("pic_group_id between", value1, value2, "picGroupId");
            return (Criteria) this;
        }

        public Criteria andPicGroupIdNotBetween(Object value1, Object value2) {
            addCriterion("pic_group_id not between", value1, value2, "picGroupId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Object value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Object value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Object value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Object value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Object value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Object value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Object> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Object> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Object value1, Object value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Object value1, Object value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andBandIdIsNull() {
            addCriterion("band_id is null");
            return (Criteria) this;
        }

        public Criteria andBandIdIsNotNull() {
            addCriterion("band_id is not null");
            return (Criteria) this;
        }

        public Criteria andBandIdEqualTo(Object value) {
            addCriterion("band_id =", value, "bandId");
            return (Criteria) this;
        }

        public Criteria andBandIdNotEqualTo(Object value) {
            addCriterion("band_id <>", value, "bandId");
            return (Criteria) this;
        }

        public Criteria andBandIdGreaterThan(Object value) {
            addCriterion("band_id >", value, "bandId");
            return (Criteria) this;
        }

        public Criteria andBandIdGreaterThanOrEqualTo(Object value) {
            addCriterion("band_id >=", value, "bandId");
            return (Criteria) this;
        }

        public Criteria andBandIdLessThan(Object value) {
            addCriterion("band_id <", value, "bandId");
            return (Criteria) this;
        }

        public Criteria andBandIdLessThanOrEqualTo(Object value) {
            addCriterion("band_id <=", value, "bandId");
            return (Criteria) this;
        }

        public Criteria andBandIdIn(List<Object> values) {
            addCriterion("band_id in", values, "bandId");
            return (Criteria) this;
        }

        public Criteria andBandIdNotIn(List<Object> values) {
            addCriterion("band_id not in", values, "bandId");
            return (Criteria) this;
        }

        public Criteria andBandIdBetween(Object value1, Object value2) {
            addCriterion("band_id between", value1, value2, "bandId");
            return (Criteria) this;
        }

        public Criteria andBandIdNotBetween(Object value1, Object value2) {
            addCriterion("band_id not between", value1, value2, "bandId");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginIsNull() {
            addCriterion("place_origin is null");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginIsNotNull() {
            addCriterion("place_origin is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginEqualTo(String value) {
            addCriterion("place_origin =", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginNotEqualTo(String value) {
            addCriterion("place_origin <>", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginGreaterThan(String value) {
            addCriterion("place_origin >", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginGreaterThanOrEqualTo(String value) {
            addCriterion("place_origin >=", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginLessThan(String value) {
            addCriterion("place_origin <", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginLessThanOrEqualTo(String value) {
            addCriterion("place_origin <=", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginLike(String value) {
            addCriterion("place_origin like", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginNotLike(String value) {
            addCriterion("place_origin not like", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginIn(List<String> values) {
            addCriterion("place_origin in", values, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginNotIn(List<String> values) {
            addCriterion("place_origin not in", values, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginBetween(String value1, String value2) {
            addCriterion("place_origin between", value1, value2, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginNotBetween(String value1, String value2) {
            addCriterion("place_origin not between", value1, value2, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andRecommendationIsNull() {
            addCriterion("recommendation is null");
            return (Criteria) this;
        }

        public Criteria andRecommendationIsNotNull() {
            addCriterion("recommendation is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendationEqualTo(String value) {
            addCriterion("recommendation =", value, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationNotEqualTo(String value) {
            addCriterion("recommendation <>", value, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationGreaterThan(String value) {
            addCriterion("recommendation >", value, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationGreaterThanOrEqualTo(String value) {
            addCriterion("recommendation >=", value, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationLessThan(String value) {
            addCriterion("recommendation <", value, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationLessThanOrEqualTo(String value) {
            addCriterion("recommendation <=", value, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationLike(String value) {
            addCriterion("recommendation like", value, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationNotLike(String value) {
            addCriterion("recommendation not like", value, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationIn(List<String> values) {
            addCriterion("recommendation in", values, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationNotIn(List<String> values) {
            addCriterion("recommendation not in", values, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationBetween(String value1, String value2) {
            addCriterion("recommendation between", value1, value2, "recommendation");
            return (Criteria) this;
        }

        public Criteria andRecommendationNotBetween(String value1, String value2) {
            addCriterion("recommendation not between", value1, value2, "recommendation");
            return (Criteria) this;
        }

        public Criteria andShelfLifeIsNull() {
            addCriterion("shelf_life is null");
            return (Criteria) this;
        }

        public Criteria andShelfLifeIsNotNull() {
            addCriterion("shelf_life is not null");
            return (Criteria) this;
        }

        public Criteria andShelfLifeEqualTo(String value) {
            addCriterion("shelf_life =", value, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeNotEqualTo(String value) {
            addCriterion("shelf_life <>", value, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeGreaterThan(String value) {
            addCriterion("shelf_life >", value, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeGreaterThanOrEqualTo(String value) {
            addCriterion("shelf_life >=", value, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeLessThan(String value) {
            addCriterion("shelf_life <", value, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeLessThanOrEqualTo(String value) {
            addCriterion("shelf_life <=", value, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeLike(String value) {
            addCriterion("shelf_life like", value, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeNotLike(String value) {
            addCriterion("shelf_life not like", value, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeIn(List<String> values) {
            addCriterion("shelf_life in", values, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeNotIn(List<String> values) {
            addCriterion("shelf_life not in", values, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeBetween(String value1, String value2) {
            addCriterion("shelf_life between", value1, value2, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andShelfLifeNotBetween(String value1, String value2) {
            addCriterion("shelf_life not between", value1, value2, "shelfLife");
            return (Criteria) this;
        }

        public Criteria andDatePackageIsNull() {
            addCriterion("date_package is null");
            return (Criteria) this;
        }

        public Criteria andDatePackageIsNotNull() {
            addCriterion("date_package is not null");
            return (Criteria) this;
        }

        public Criteria andDatePackageEqualTo(Date value) {
            addCriterionForJDBCDate("date_package =", value, "datePackage");
            return (Criteria) this;
        }

        public Criteria andDatePackageNotEqualTo(Date value) {
            addCriterionForJDBCDate("date_package <>", value, "datePackage");
            return (Criteria) this;
        }

        public Criteria andDatePackageGreaterThan(Date value) {
            addCriterionForJDBCDate("date_package >", value, "datePackage");
            return (Criteria) this;
        }

        public Criteria andDatePackageGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_package >=", value, "datePackage");
            return (Criteria) this;
        }

        public Criteria andDatePackageLessThan(Date value) {
            addCriterionForJDBCDate("date_package <", value, "datePackage");
            return (Criteria) this;
        }

        public Criteria andDatePackageLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_package <=", value, "datePackage");
            return (Criteria) this;
        }

        public Criteria andDatePackageIn(List<Date> values) {
            addCriterionForJDBCDate("date_package in", values, "datePackage");
            return (Criteria) this;
        }

        public Criteria andDatePackageNotIn(List<Date> values) {
            addCriterionForJDBCDate("date_package not in", values, "datePackage");
            return (Criteria) this;
        }

        public Criteria andDatePackageBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_package between", value1, value2, "datePackage");
            return (Criteria) this;
        }

        public Criteria andDatePackageNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_package not between", value1, value2, "datePackage");
            return (Criteria) this;
        }

        public Criteria andDatePresellIsNull() {
            addCriterion("date_presell is null");
            return (Criteria) this;
        }

        public Criteria andDatePresellIsNotNull() {
            addCriterion("date_presell is not null");
            return (Criteria) this;
        }

        public Criteria andDatePresellEqualTo(Date value) {
            addCriterionForJDBCDate("date_presell =", value, "datePresell");
            return (Criteria) this;
        }

        public Criteria andDatePresellNotEqualTo(Date value) {
            addCriterionForJDBCDate("date_presell <>", value, "datePresell");
            return (Criteria) this;
        }

        public Criteria andDatePresellGreaterThan(Date value) {
            addCriterionForJDBCDate("date_presell >", value, "datePresell");
            return (Criteria) this;
        }

        public Criteria andDatePresellGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_presell >=", value, "datePresell");
            return (Criteria) this;
        }

        public Criteria andDatePresellLessThan(Date value) {
            addCriterionForJDBCDate("date_presell <", value, "datePresell");
            return (Criteria) this;
        }

        public Criteria andDatePresellLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_presell <=", value, "datePresell");
            return (Criteria) this;
        }

        public Criteria andDatePresellIn(List<Date> values) {
            addCriterionForJDBCDate("date_presell in", values, "datePresell");
            return (Criteria) this;
        }

        public Criteria andDatePresellNotIn(List<Date> values) {
            addCriterionForJDBCDate("date_presell not in", values, "datePresell");
            return (Criteria) this;
        }

        public Criteria andDatePresellBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_presell between", value1, value2, "datePresell");
            return (Criteria) this;
        }

        public Criteria andDatePresellNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_presell not between", value1, value2, "datePresell");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryIsNull() {
            addCriterion("date_delivery is null");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryIsNotNull() {
            addCriterion("date_delivery is not null");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryEqualTo(Date value) {
            addCriterionForJDBCDate("date_delivery =", value, "dateDelivery");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryNotEqualTo(Date value) {
            addCriterionForJDBCDate("date_delivery <>", value, "dateDelivery");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryGreaterThan(Date value) {
            addCriterionForJDBCDate("date_delivery >", value, "dateDelivery");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_delivery >=", value, "dateDelivery");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryLessThan(Date value) {
            addCriterionForJDBCDate("date_delivery <", value, "dateDelivery");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date_delivery <=", value, "dateDelivery");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryIn(List<Date> values) {
            addCriterionForJDBCDate("date_delivery in", values, "dateDelivery");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryNotIn(List<Date> values) {
            addCriterionForJDBCDate("date_delivery not in", values, "dateDelivery");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_delivery between", value1, value2, "dateDelivery");
            return (Criteria) this;
        }

        public Criteria andDateDeliveryNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date_delivery not between", value1, value2, "dateDelivery");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNull() {
            addCriterion("original_price is null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNotNull() {
            addCriterion("original_price is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceEqualTo(Double value) {
            addCriterion("original_price =", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotEqualTo(Double value) {
            addCriterion("original_price <>", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThan(Double value) {
            addCriterion("original_price >", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("original_price >=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThan(Double value) {
            addCriterion("original_price <", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThanOrEqualTo(Double value) {
            addCriterion("original_price <=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIn(List<Double> values) {
            addCriterion("original_price in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotIn(List<Double> values) {
            addCriterion("original_price not in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceBetween(Double value1, Double value2) {
            addCriterion("original_price between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotBetween(Double value1, Double value2) {
            addCriterion("original_price not between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("unit is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("unit is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("unit =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("unit <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("unit >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("unit >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("unit <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("unit <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("unit like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("unit not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("unit in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("unit not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("unit between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("unit not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("rank is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("rank is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(Integer value) {
            addCriterion("rank =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(Integer value) {
            addCriterion("rank <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(Integer value) {
            addCriterion("rank >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("rank >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(Integer value) {
            addCriterion("rank <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(Integer value) {
            addCriterion("rank <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<Integer> values) {
            addCriterion("rank in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<Integer> values) {
            addCriterion("rank not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(Integer value1, Integer value2) {
            addCriterion("rank between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(Integer value1, Integer value2) {
            addCriterion("rank not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andStockIsNull() {
            addCriterion("stock is null");
            return (Criteria) this;
        }

        public Criteria andStockIsNotNull() {
            addCriterion("stock is not null");
            return (Criteria) this;
        }

        public Criteria andStockEqualTo(Integer value) {
            addCriterion("stock =", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotEqualTo(Integer value) {
            addCriterion("stock <>", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThan(Integer value) {
            addCriterion("stock >", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock >=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThan(Integer value) {
            addCriterion("stock <", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThanOrEqualTo(Integer value) {
            addCriterion("stock <=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockIn(List<Integer> values) {
            addCriterion("stock in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotIn(List<Integer> values) {
            addCriterion("stock not in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockBetween(Integer value1, Integer value2) {
            addCriterion("stock between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotBetween(Integer value1, Integer value2) {
            addCriterion("stock not between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfIsNull() {
            addCriterion("status_on_shelf is null");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfIsNotNull() {
            addCriterion("status_on_shelf is not null");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfEqualTo(String value) {
            addCriterion("status_on_shelf =", value, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfNotEqualTo(String value) {
            addCriterion("status_on_shelf <>", value, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfGreaterThan(String value) {
            addCriterion("status_on_shelf >", value, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfGreaterThanOrEqualTo(String value) {
            addCriterion("status_on_shelf >=", value, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfLessThan(String value) {
            addCriterion("status_on_shelf <", value, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfLessThanOrEqualTo(String value) {
            addCriterion("status_on_shelf <=", value, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfLike(String value) {
            addCriterion("status_on_shelf like", value, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfNotLike(String value) {
            addCriterion("status_on_shelf not like", value, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfIn(List<String> values) {
            addCriterion("status_on_shelf in", values, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfNotIn(List<String> values) {
            addCriterion("status_on_shelf not in", values, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfBetween(String value1, String value2) {
            addCriterion("status_on_shelf between", value1, value2, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andStatusOnShelfNotBetween(String value1, String value2) {
            addCriterion("status_on_shelf not between", value1, value2, "statusOnShelf");
            return (Criteria) this;
        }

        public Criteria andProviderIdIsNull() {
            addCriterion("provider_id is null");
            return (Criteria) this;
        }

        public Criteria andProviderIdIsNotNull() {
            addCriterion("provider_id is not null");
            return (Criteria) this;
        }

        public Criteria andProviderIdEqualTo(Object value) {
            addCriterion("provider_id =", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdNotEqualTo(Object value) {
            addCriterion("provider_id <>", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdGreaterThan(Object value) {
            addCriterion("provider_id >", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdGreaterThanOrEqualTo(Object value) {
            addCriterion("provider_id >=", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdLessThan(Object value) {
            addCriterion("provider_id <", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdLessThanOrEqualTo(Object value) {
            addCriterion("provider_id <=", value, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdIn(List<Object> values) {
            addCriterion("provider_id in", values, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdNotIn(List<Object> values) {
            addCriterion("provider_id not in", values, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdBetween(Object value1, Object value2) {
            addCriterion("provider_id between", value1, value2, "providerId");
            return (Criteria) this;
        }

        public Criteria andProviderIdNotBetween(Object value1, Object value2) {
            addCriterion("provider_id not between", value1, value2, "providerId");
            return (Criteria) this;
        }

        public Criteria andAuditIdIsNull() {
            addCriterion("audit_id is null");
            return (Criteria) this;
        }

        public Criteria andAuditIdIsNotNull() {
            addCriterion("audit_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuditIdEqualTo(Object value) {
            addCriterion("audit_id =", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdNotEqualTo(Object value) {
            addCriterion("audit_id <>", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdGreaterThan(Object value) {
            addCriterion("audit_id >", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdGreaterThanOrEqualTo(Object value) {
            addCriterion("audit_id >=", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdLessThan(Object value) {
            addCriterion("audit_id <", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdLessThanOrEqualTo(Object value) {
            addCriterion("audit_id <=", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdIn(List<Object> values) {
            addCriterion("audit_id in", values, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdNotIn(List<Object> values) {
            addCriterion("audit_id not in", values, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdBetween(Object value1, Object value2) {
            addCriterion("audit_id between", value1, value2, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdNotBetween(Object value1, Object value2) {
            addCriterion("audit_id not between", value1, value2, "auditId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterionForJDBCDate("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterionForJDBCDate("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterionForJDBCDate("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.production
     *
     * @mbg.generated do_not_delete_during_merge Fri Jan 22 17:52:23 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 22 17:52:23 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}