package com.myfarm.flashsale.core.modules.site.repository.mappers;

import com.myfarm.flashsale.core.modules.site.model.Site;
import com.myfarm.flashsale.core.modules.site.model.SiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    long countByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    int deleteByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    int deleteByPrimaryKey(Object siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    int insert(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    int insertSelective(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    List<Site> selectByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    Site selectByPrimaryKey(Object siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    int updateByExampleSelective(@Param("record") Site record, @Param("example") SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    int updateByExample(@Param("record") Site record, @Param("example") SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    int updateByPrimaryKeySelective(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.site
     *
     * @mbg.generated Fri Jan 22 17:56:43 CST 2021
     */
    int updateByPrimaryKey(Site record);
}