package com.myfarm.flashsale.core.modules.audit.model;

import java.util.Date;

public class Audit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audit.audit_id
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    private Object auditId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audit.status
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audit.auditor
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    private String auditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audit.employee_id
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audit.comments
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audit.create_date
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.audit.update_date
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audit.audit_id
     *
     * @return the value of public.audit.audit_id
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public Object getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audit.audit_id
     *
     * @param auditId the value for public.audit.audit_id
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public void setAuditId(Object auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audit.status
     *
     * @return the value of public.audit.status
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audit.status
     *
     * @param status the value for public.audit.status
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audit.auditor
     *
     * @return the value of public.audit.auditor
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audit.auditor
     *
     * @param auditor the value for public.audit.auditor
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audit.employee_id
     *
     * @return the value of public.audit.employee_id
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audit.employee_id
     *
     * @param employeeId the value for public.audit.employee_id
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audit.comments
     *
     * @return the value of public.audit.comments
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audit.comments
     *
     * @param comments the value for public.audit.comments
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audit.create_date
     *
     * @return the value of public.audit.create_date
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audit.create_date
     *
     * @param createDate the value for public.audit.create_date
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.audit.update_date
     *
     * @return the value of public.audit.update_date
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.audit.update_date
     *
     * @param updateDate the value for public.audit.update_date
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}