package com.myfarm.flashsale.core.modules.cart.model;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cart.cart_id
     *
     * @mbg.generated Fri Jan 22 17:47:39 CST 2021
     */
    private Object cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cart.user_id
     *
     * @mbg.generated Fri Jan 22 17:47:39 CST 2021
     */
    private Object userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cart.cart_id
     *
     * @return the value of public.cart.cart_id
     *
     * @mbg.generated Fri Jan 22 17:47:39 CST 2021
     */
    public Object getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cart.cart_id
     *
     * @param cartId the value for public.cart.cart_id
     *
     * @mbg.generated Fri Jan 22 17:47:39 CST 2021
     */
    public void setCartId(Object cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cart.user_id
     *
     * @return the value of public.cart.user_id
     *
     * @mbg.generated Fri Jan 22 17:47:39 CST 2021
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cart.user_id
     *
     * @param userId the value for public.cart.user_id
     *
     * @mbg.generated Fri Jan 22 17:47:39 CST 2021
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }
}