package com.myfarm.flashsale.core.modules.cart.model;

import java.util.Date;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cart.cart_item_id
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    private Object cartItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cart.user_id
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cart.production_id
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    private Object productionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cart.quantity
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.cart.add_cart_date
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    private Date addCartDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cart.cart_item_id
     *
     * @return the value of public.cart.cart_item_id
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    public Object getCartItemId() {
        return cartItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cart.cart_item_id
     *
     * @param cartItemId the value for public.cart.cart_item_id
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    public void setCartItemId(Object cartItemId) {
        this.cartItemId = cartItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cart.user_id
     *
     * @return the value of public.cart.user_id
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cart.user_id
     *
     * @param userId the value for public.cart.user_id
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cart.production_id
     *
     * @return the value of public.cart.production_id
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    public Object getProductionId() {
        return productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cart.production_id
     *
     * @param productionId the value for public.cart.production_id
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    public void setProductionId(Object productionId) {
        this.productionId = productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cart.quantity
     *
     * @return the value of public.cart.quantity
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cart.quantity
     *
     * @param quantity the value for public.cart.quantity
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.cart.add_cart_date
     *
     * @return the value of public.cart.add_cart_date
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    public Date getAddCartDate() {
        return addCartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.cart.add_cart_date
     *
     * @param addCartDate the value for public.cart.add_cart_date
     *
     * @mbg.generated Mon Feb 01 15:20:44 CST 2021
     */
    public void setAddCartDate(Date addCartDate) {
        this.addCartDate = addCartDate;
    }
}