package com.myfarm.flashsale.core.modules.production.repository.mappers;

import com.myfarm.flashsale.core.modules.production.model.Production;
import com.myfarm.flashsale.core.modules.production.model.ProductionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    long countByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    int deleteByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    int deleteByPrimaryKey(Object productionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    int insert(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    int insertSelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    List<Production> selectByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    Production selectByPrimaryKey(Object productionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") Production record, @Param("example") ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    int updateByExample(@Param("record") Production record, @Param("example") ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    int updateByPrimaryKeySelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.production
     *
     * @mbg.generated Fri Jan 29 14:54:28 CST 2021
     */
    int updateByPrimaryKey(Production record);
}