package com.myfarm.flashsale.core.modules.audit.repository.mappers;

import com.myfarm.flashsale.core.modules.audit.model.Audit;
import com.myfarm.flashsale.core.modules.audit.model.AuditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    long countByExample(AuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:36 CST 2021
     */
    int deleteByExample(AuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:37 CST 2021
     */
    int deleteByPrimaryKey(Object auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:37 CST 2021
     */
    int insert(Audit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:37 CST 2021
     */
    int insertSelective(Audit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:37 CST 2021
     */
    List<Audit> selectByExample(AuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:37 CST 2021
     */
    Audit selectByPrimaryKey(Object auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:37 CST 2021
     */
    int updateByExampleSelective(@Param("record") Audit record, @Param("example") AuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:37 CST 2021
     */
    int updateByExample(@Param("record") Audit record, @Param("example") AuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:37 CST 2021
     */
    int updateByPrimaryKeySelective(Audit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.audit
     *
     * @mbg.generated Fri Jan 22 17:32:37 CST 2021
     */
    int updateByPrimaryKey(Audit record);
}