package com.myfarm.flashsale.core.modules.provider.repository.mappers;

import com.myfarm.flashsale.core.modules.provider.model.Provider;
import com.myfarm.flashsale.core.modules.provider.model.ProviderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProviderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    long countByExample(ProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    int deleteByExample(ProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    int deleteByPrimaryKey(Object providerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    int insert(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    int insertSelective(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    List<Provider> selectByExample(ProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    Provider selectByPrimaryKey(Object providerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") Provider record, @Param("example") ProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    int updateByExample(@Param("record") Provider record, @Param("example") ProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    int updateByPrimaryKeySelective(Provider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.provider
     *
     * @mbg.generated Fri Jan 22 17:53:30 CST 2021
     */
    int updateByPrimaryKey(Provider record);
}